'use strict';

/**
 * Fixture invariants for the three committed workbooks.
 *
 * The file pins each workbook's row count, its `Student ID` key set, the
 * header cells the loaders validate, the ZIP container integrity the reader
 * verifies, and its own SHA-256. A binary fixture produces no reviewable diff,
 * so its digest is its only drift detector, and equally the proof that the
 * feature changed no byte of it.
 *
 * The container assertions are deliberately made WITHOUT `lib/workbook.js`:
 * they walk the ZIP records themselves, so they state a fact about the
 * committed bytes rather than about the reader, which is what makes the
 * reader's own integrity checks - local header against central record, and the
 * recorded CRC-32 against the inflated data - meaningful rather than vacuous. A
 * workbook regenerated by a tool that stores no checksum fails here, naming the
 * missing field, instead of surfacing as an unexplained startup failure.
 *
 * All four tests are top level, with no subtest, `describe`, `it` or hook: the
 * guarded runner counts passing tests against a fixed floor, and an assertion
 * made inside a hook is not counted at all, so multi-case behaviour goes in a
 * case table inside a test body. Every assertion is a pure read - no socket,
 * no child process, no write of any kind - so nothing needs tearing down, and
 * the contents of `activities.json` are not this file's subject.
 */

const { test } = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const zlib = require('node:zlib');

const { readWorksheetRows } = require('../lib/workbook');

const REPO_ROOT = path.resolve(__dirname, '..');

/**
 * The fixture table, serving all four tests. `headers` pins only the cells this
 * suite depends on; for the two workbooks the service opens they are exactly
 * the cells `lib/studentDirectory.js` and `lib/activityRepository.js` validate
 * at load, so a mismatch here explains a startup failure there. Labels outside
 * that set are not asserted one by one - the reader parses the whole worksheet
 * either way, and `digest` catches any change to a workbook's bytes.
 */
const WORKBOOKS = [
  {
    file: 'student_details.xlsx',
    sheet: 'Student Details',
    digest: '3923e3d75215b4f110737ddd7793cddc045cb232c7f11618314791daa51c68fa',
    headers: { A: 'Student ID', B: 'Name' }
  },
  {
    // Read by this suite only - the service never opens it. Its key column is
    // what makes the cross-workbook key-set invariant assertable at all.
    file: 'student_academics.xlsx',
    sheet: 'Academics',
    digest: 'd37bbe402609edbb18a6c6056cf662f55b82ec4be1b7ddcce0070a3a97aa0285',
    headers: { A: 'Student ID' }
  },
  {
    file: 'student_other_info.xlsx',
    sheet: 'Other Info',
    digest: 'b61f46c0f6b6350c2aa908e89367b745d611ca1d94b5eca65aabff9a617f9eb0',
    headers: { A: 'Student ID', C: 'Extracurricular Activity' }
  }
];

/**
 * The key space, written out literally rather than generated, so the assertion
 * states the contract instead of restating whatever the file happens to hold.
 * Listed in ascending order, which is what lets a sorted copy of a workbook's
 * keys be compared against it without regard to row order.
 */
const EXPECTED_IDS = [
  'S001',
  'S002',
  'S003',
  'S004',
  'S005',
  'S006',
  'S007',
  'S008',
  'S009',
  'S010'
];

const EXPECTED_ROW_COUNT = 11;

const TMP_ARTIFACT_NAME = 'activities.json.tmp';

/**
 * The worksheet part each package carries exactly one of, and the ZIP record
 * signatures and fixed record sizes needed to find it. These are restated here
 * rather than imported because the point of the container assertions is to
 * describe the committed bytes independently of the module that reads them.
 */
const WORKSHEET_PART = 'xl/worksheets/sheet1.xml';
const END_OF_CENTRAL_DIRECTORY_SIGNATURE = 0x06054b50;
const CENTRAL_FILE_HEADER_SIGNATURE = 0x02014b50;
const LOCAL_FILE_HEADER_SIGNATURE = 0x04034b50;
const END_OF_CENTRAL_DIRECTORY_SIZE = 22;
const CENTRAL_FILE_HEADER_SIZE = 46;
const LOCAL_FILE_HEADER_SIZE = 30;

/** The largest trailing archive comment a ZIP may carry, bounding the scan. */
const MAX_ARCHIVE_COMMENT = 65535;

/** The compression method every entry in all three packages uses: DEFLATE. */
const METHOD_DEFLATE = 8;

/**
 * A short, stable token naming this checkout, so two working trees of this
 * repository never share a temporary namespace: twelve hex characters of a
 * SHA-256 over the absolute path of its root. The path is lower-cased first
 * because path comparison is case-insensitive on this platform, so a
 * differently-cased path to the same tree yields the same token.
 */
const CHECKOUT_TOKEN = crypto
  .createHash('sha256')
  .update(REPO_ROOT.toLowerCase())
  .digest('hex')
  .slice(0, 12);

/**
 * The namespace every throwaway registry directory `test/activities.test.js`
 * creates carries. `os.tmpdir()` is host-wide and shared with other checkouts
 * and processes, so embedding `CHECKOUT_TOKEN` keeps the namespace private to
 * this working tree and the leftover assertion covers only the directories this
 * suite created. The derivation is duplicated rather than shared because every
 * `.js` file inside a directory named `test/` runs as a test under default
 * discovery, so no helper module can hold it, and the two files run in separate
 * child processes; it must stay in step with `test/activities.test.js`, or the
 * leftover check can never fail.
 */
const TEMP_NAMESPACE = `student-activities-${CHECKOUT_TOKEN}-`;

/**
 * The OWNER SEGMENT `test/activities.test.js` writes immediately after the
 * namespace: `p`, the pid of the process that created the directory, and a
 * hyphen, before `fs.mkdtempSync`'s own random characters. Matched against the
 * remainder of an entry name once the namespace has been stripped, so the
 * captured group is the owning pid in decimal. The two files MUST STAY IN STEP
 * on this shape as well as on the namespace: an owner this pattern cannot read
 * is classified as a leftover, which is the safe direction - a convention
 * changed on one side alone fails loudly here instead of silently passing.
 */
const TEMP_OWNER_PATTERN = /^p(\d+)-/;

/**
 * The only directories the artifact walk does not descend into. Both are
 * machine-managed and neither can hold a registry write: `.git` is object
 * storage and `node_modules` is an install target this dependency-free project
 * never populates. Everything else under the checkout is inspected.
 */
const SKIPPED_DIRECTORIES = new Set(['.git', 'node_modules']);

/**
 * Runaway stop for the artifact walk, not a scope limit. The checkout is two
 * levels deep (`lib/`, `test/`) and symlinks are never followed, so a finite
 * tree cannot reach this depth; exceeding it means the walk is looping, which
 * is a fault. It therefore THROWS rather than returning - a bound that returns
 * "nothing found" would report a tree it never finished walking as clean.
 */
const WALK_DEPTH_LIMIT = 64;

const rowsOf = (file) => readWorksheetRows(path.join(REPO_ROOT, file));

const digestOf = (absolutePath) =>
  crypto.createHash('sha256').update(fs.readFileSync(absolutePath)).digest('hex');

/**
 * Reads the worksheet entry's ZIP metadata and compressed bytes straight out of
 * a workbook, walking the records here rather than through
 * `lib/workbook.js` - so what the container assertions state is a property of the committed
 * file and not an echo of the reader's own behaviour.
 *
 * The walk is the minimum needed to reach one named entry: scan backwards for
 * the end-of-central-directory record, bounded by its own size plus the largest
 * archive comment a ZIP may carry; read the entry count and the directory
 * offset from it; then step through the directory until the worksheet part is
 * matched by name. Anything that prevents that - no record, a wrong signature,
 * no such entry - throws with the file named, which fails the test that called
 * it.
 *
 * @param {string} absolutePath Path to the `.xlsx` file.
 * @returns {{central: {name: string, flags: number, method: number, crc32: number,
 *   compressedSize: number, uncompressedSize: number},
 *   local: {name: string, flags: number, method: number, crc32: number,
 *   compressedSize: number, uncompressedSize: number}, compressed: Buffer}} The
 *   worksheet entry as each of the two headers describes it, and its stored bytes.
 */
const inspectWorksheetEntry = (absolutePath) => {
  const bytes = fs.readFileSync(absolutePath);

  let end = -1;
  const lowest = Math.max(
    0,
    bytes.length - (END_OF_CENTRAL_DIRECTORY_SIZE + MAX_ARCHIVE_COMMENT)
  );
  for (let at = bytes.length - END_OF_CENTRAL_DIRECTORY_SIZE; at >= lowest; at -= 1) {
    if (bytes.readUInt32LE(at) === END_OF_CENTRAL_DIRECTORY_SIGNATURE) {
      end = at;
      break;
    }
  }
  if (end === -1) {
    throw new Error(`${absolutePath} carries no ZIP end-of-central-directory record`);
  }

  const entryCount = bytes.readUInt16LE(end + 10);
  let at = bytes.readUInt32LE(end + 16);
  for (let index = 0; index < entryCount; index += 1) {
    if (bytes.readUInt32LE(at) !== CENTRAL_FILE_HEADER_SIGNATURE) {
      throw new Error(
        `${absolutePath} central directory entry ${index} has an unexpected signature`
      );
    }
    const nameLength = bytes.readUInt16LE(at + 28);
    const nameAt = at + CENTRAL_FILE_HEADER_SIZE;
    const name = bytes.toString('utf8', nameAt, nameAt + nameLength);

    if (name === WORKSHEET_PART) {
      const central = {
        name,
        flags: bytes.readUInt16LE(at + 8),
        method: bytes.readUInt16LE(at + 10),
        crc32: bytes.readUInt32LE(at + 16),
        compressedSize: bytes.readUInt32LE(at + 20),
        uncompressedSize: bytes.readUInt32LE(at + 24)
      };

      const localAt = bytes.readUInt32LE(at + 42);
      if (bytes.readUInt32LE(localAt) !== LOCAL_FILE_HEADER_SIGNATURE) {
        throw new Error(
          `${absolutePath} worksheet local file header has an unexpected signature`
        );
      }
      const localNameLength = bytes.readUInt16LE(localAt + 26);
      const localNameAt = localAt + LOCAL_FILE_HEADER_SIZE;
      const local = {
        name: bytes.toString('utf8', localNameAt, localNameAt + localNameLength),
        flags: bytes.readUInt16LE(localAt + 6),
        method: bytes.readUInt16LE(localAt + 8),
        crc32: bytes.readUInt32LE(localAt + 14),
        compressedSize: bytes.readUInt32LE(localAt + 18),
        uncompressedSize: bytes.readUInt32LE(localAt + 22)
      };

      const dataAt = localNameAt + localNameLength + bytes.readUInt16LE(localAt + 28);
      return {
        central,
        local,
        compressed: bytes.subarray(dataAt, dataAt + central.compressedSize)
      };
    }

    at +=
      CENTRAL_FILE_HEADER_SIZE +
      nameLength +
      bytes.readUInt16LE(at + 30) +
      bytes.readUInt16LE(at + 32);
  }
  throw new Error(`${absolutePath} declares no ${WORKSHEET_PART} entry`);
};

/**
 * Walks a directory tree collecting every `activities.json.tmp` left behind,
 * and every directory it could not inspect: "found no artifact" means nothing
 * until everything that could hold one has been read, so an uninspected
 * directory fails the assertion exactly as a found artifact does.
 *
 * `.git` and `node_modules` are the only directories skipped. A symlink or
 * Windows junction is not descended into - `Dirent.isDirectory()` is false for
 * one - which keeps the walk finite and inside this tree, while a link whose
 * target lies within the checkout is still covered, reached as a real
 * directory. `ENOENT` below the root is the one benign listing failure, an
 * entry that disappeared between the `readdir` naming it and the descent into
 * it holding nothing; `ENOENT` on the root and every other error - `EACCES`,
 * `EPERM`, `ENOTDIR` - leaves real contents unread and is reported unverified.
 *
 * @param {string} dir Absolute path of the directory to walk.
 * @param {number} [depth] Current recursion depth; callers pass nothing.
 * @returns {{artifacts: string[], unverified: string[]}} Absolute paths of the
 *   artifacts found, and `path (CODE)` for every directory left uninspected.
 */
const findTmpArtifacts = (dir, depth = 0) => {
  if (depth > WALK_DEPTH_LIMIT) {
    throw new Error(
      `artifact walk exceeded ${WALK_DEPTH_LIMIT} levels at ${dir}; the checkout ` +
        'is two levels deep, so the walk is following a cycle rather than a tree'
    );
  }

  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (cause) {
    const code =
      cause !== null && typeof cause === 'object' && cause.code !== undefined
        ? String(cause.code)
        : 'UNKNOWN';
    if (code === 'ENOENT' && depth > 0) return { artifacts: [], unverified: [] };
    return { artifacts: [], unverified: [`${dir} (${code})`] };
  }

  const found = { artifacts: [], unverified: [] };
  for (const entry of entries) {
    const absolute = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (SKIPPED_DIRECTORIES.has(entry.name)) continue;
      const nested = findTmpArtifacts(absolute, depth + 1);
      found.artifacts.push(...nested.artifacts);
      found.unverified.push(...nested.unverified);
      continue;
    }
    if (entry.name === TMP_ARTIFACT_NAME) found.artifacts.push(absolute);
  }
  return found;
};

/**
 * Splits this checkout's temporary-directory entries into the ones a live
 * sibling process is legitimately using and the ones nothing owns any more,
 * which are the leftovers the suite failed to clean up.
 *
 * Only the second class is a fault. Under `node --test` at its default
 * concurrency `test/activities.test.js` runs in a child process alongside this
 * one and is mid-use of its registry directories, so matching the namespace
 * alone reports a working directory as a leak; under the serialized runner
 * `verify-tests.js` uses, that process has already exited and every directory
 * it left behind is attributed to a dead owner and reported.
 *
 * Liveness is probed with `process.kill(pid, 0)`, which sends no signal and
 * only asks the kernel about the pid. It has three outcomes and all three are
 * handled: a normal return means the process exists; `EPERM` means it exists
 * but this account may not signal it, which is ALIVE and must not be read as
 * dead; `ESRCH` means no such process, so the directory is a leftover. Any
 * other error is not evidence of liveness either and is treated the same way.
 *
 * An entry whose owner segment cannot be parsed - an old-format name predating
 * the convention, or a directory created by something else inside this
 * namespace - is a leftover, as is one owned by THIS process: this file creates
 * no temporary directory, so its own pid appearing there is a fault, and
 * treating it as "alive" would be a hole in the check.
 *
 * @param {string[]} names `os.tmpdir()` entry names, unfiltered.
 * @returns {{leftovers: string[], liveSiblings: string[]}} The names of this
 *   checkout's entries in each class, in `readdir` order.
 */
const classifyTempEntries = (names) => {
  const classified = { leftovers: [], liveSiblings: [] };
  for (const name of names) {
    if (!name.startsWith(TEMP_NAMESPACE)) continue;
    const owner = TEMP_OWNER_PATTERN.exec(name.slice(TEMP_NAMESPACE.length));
    const pid = owner === null ? Number.NaN : Number(owner[1]);
    if (!Number.isSafeInteger(pid) || pid <= 0 || pid === process.pid) {
      classified.leftovers.push(name);
      continue;
    }
    let alive;
    try {
      process.kill(pid, 0);
      alive = true;
    } catch (cause) {
      const code =
        cause !== null && typeof cause === 'object' && cause.code !== undefined
          ? String(cause.code)
          : 'UNKNOWN';
      alive = code === 'EPERM';
    }
    if (alive) classified.liveSiblings.push(name);
    else classified.leftovers.push(name);
  }
  return classified;
};

test('every workbook holds a header row plus ten student records', () => {
  for (const { file, sheet, headers } of WORKBOOKS) {
    const rows = rowsOf(file);
    assert.equal(
      rows.length,
      EXPECTED_ROW_COUNT,
      `${file} (${sheet}) must hold ${EXPECTED_ROW_COUNT} rows, read ${rows.length}`
    );
    // A reader that silently dropped the header would still return ten data
    // rows, so the header row is asserted here.
    assert.ok(
      rows[0] !== undefined && typeof rows[0] === 'object',
      `${file} (${sheet}) must expose a header row at index 0`
    );
    assert.notEqual(
      rows[0].A,
      '',
      `${file} (${sheet}) header cell A1 must be populated, read an empty cell`
    );
    assert.equal(
      typeof rows[0].A,
      'string',
      `${file} (${sheet}) header cell A1 must be a string, read ${typeof rows[0].A}`
    );
    assert.equal(
      Object.keys(headers).every((column) => typeof rows[0][column] === 'string'),
      true,
      `${file} (${sheet}) must expose every pinned header column as a string`
    );

    // The shape of what the reader returned, asserted against the real bytes
    // rather than against a synthetic sheet. `lib/workbook.js` refuses a cell
    // whose `r` attribute is not a complete column-letters-plus-row-number
    // reference, so a key here that is not column letters would mean a
    // malformed reference had been accepted and had claimed a real column.
    rows.forEach((parsed, offset) => {
      for (const [column, value] of Object.entries(parsed)) {
        assert.match(
          column,
          /^[A-Z]{1,3}$/,
          `${file} (${sheet}) row ${offset + 1} is keyed by '${column}', which is not ` +
            'a column letter'
        );
        assert.equal(
          typeof value,
          'string',
          `${file} (${sheet}) cell ${column}${offset + 1} must be a string, read ` +
            `${typeof value}`
        );
      }
    });

    // Every column this feature depends on is populated in every data row, so
    // a blank one would mean the reader dropped a cell it had parsed - the
    // failure that would silently shorten a student's activity list.
    for (let index = 1; index < rows.length; index += 1) {
      for (const column of Object.keys(headers)) {
        assert.notEqual(
          rows[index][column],
          '',
          `${file} (${sheet}) cell ${column}${index + 1} must be populated, read an ` +
            'empty cell'
        );
      }
    }
  }
});

// The comparison is on sorted copies, because what the feature depends on is
// the set of keys each file carries rather than the order its rows sit in:
// nothing in `lib/studentDirectory.js` or `lib/activityRepository.js` reads a
// key by position. Sorting copies rather than building sets keeps it a
// multiset comparison, so a duplicated or missing key still fails.
test('every workbook carries the identical Student ID key set S001 to S010', () => {
  const collected = WORKBOOKS.map(({ file, sheet }) => {
    const keys = rowsOf(file)
      .slice(1)
      .map((row) => row.A);
    return { file, sheet, keys, sortedKeys: [...keys].sort() };
  });

  for (const { file, sheet, keys, sortedKeys } of collected) {
    assert.deepEqual(
      sortedKeys,
      EXPECTED_IDS,
      `${file} (${sheet}) column A rows 2-${EXPECTED_ROW_COUNT} must be the set ` +
        `${EXPECTED_IDS.join(', ')} in any order, read ${keys.join(', ')}`
    );
  }

  // Equality with EXPECTED_IDS already implies cross-file identity, but the
  // pairwise comparison is stated explicitly so a failure names the two files
  // that disagree - that is the fact `lib/activityRepository.js` relies on
  // when it refuses an activity row whose key is absent from the directory.
  const pairs = collected.flatMap((left, index) =>
    collected.slice(index + 1).map((right) => [left, right])
  );
  for (const [left, right] of pairs) {
    assert.deepEqual(
      left.sortedKeys,
      right.sortedKeys,
      `${left.file} and ${right.file} must carry identical Student ID sets; ` +
        `read ${left.keys.join(', ')} against ${right.keys.join(', ')}`
    );
  }
});

test('every workbook header names the columns the service reads', () => {
  for (const { file, sheet, headers } of WORKBOOKS) {
    const header = rowsOf(file)[0];
    for (const [column, label] of Object.entries(headers)) {
      assert.equal(
        header[column],
        label,
        `${file} (${sheet}) header cell ${column}1 must be '${label}', ` +
          `read '${header[column]}'`
      );
      // Exactly as stored: no trimming, no case folding, no collapsing of
      // interior spaces. `Attendance %` and `Extracurricular Activity` are
      // compared byte for byte by the loaders, so any normalisation the reader
      // applied here would turn into a startup failure there.
      assert.equal(
        header[column].length,
        label.length,
        `${file} (${sheet}) header cell ${column}1 must be stored verbatim; read ` +
          `${header[column].length} characters against ${label.length}`
      );
    }

    // Reading the same file twice must produce the same rows. The reader holds
    // no module-level parse state - no pattern carrying `lastIndex` between
    // calls, no cache - so two reads of one snapshot cannot diverge, and the
    // two loaders that each read their own workbook cannot interfere.
    assert.deepEqual(
      rowsOf(file),
      rowsOf(file),
      `${file} (${sheet}) must read identically twice in a row`
    );
  }
});

test('committed workbooks match their baseline digests and leave no temporary artifact', () => {
  for (const { file, sheet, digest } of WORKBOOKS) {
    const actual = digestOf(path.join(REPO_ROOT, file));
    assert.equal(
      actual,
      digest,
      `${file} (${sheet}) drifted from its committed baseline: ` +
        `expected SHA-256 ${digest}, read ${actual}`
    );
  }

  // The digests above prove the bytes did not drift. These prove the property
  // the reader depends on is actually present in them: `lib/workbook.js`
  // refuses a worksheet entry whose local header disagrees with the central
  // record, whose data does not hash to the recorded CRC-32, or whose DEFLATE
  // stream has bytes after it. A fixture regenerated by a writer that stored no
  // checksum, or that streamed the entry and left the central record behind,
  // would make the service refuse to start - so it fails here instead, naming
  // the field that changed.
  for (const { file, sheet } of WORKBOOKS) {
    const absolute = path.join(REPO_ROOT, file);
    const { central, local, compressed } = inspectWorksheetEntry(absolute);

    assert.equal(
      central.method,
      METHOD_DEFLATE,
      `${file} (${sheet}) ${WORKSHEET_PART} must be DEFLATE-compressed (method ` +
        `${METHOD_DEFLATE}), read method ${central.method}`
    );
    for (const field of [
      'name',
      'flags',
      'method',
      'crc32',
      'compressedSize',
      'uncompressedSize'
    ]) {
      assert.equal(
        local[field],
        central[field],
        `${file} (${sheet}) ${WORKSHEET_PART} must declare the same ${field} in its ` +
          `local file header and its central directory record; read ` +
          `${local[field]} against ${central[field]}`
      );
    }

    let inflated;
    try {
      inflated = zlib.inflateRawSync(compressed, { rejectGarbageAfterEnd: true });
    } catch (cause) {
      assert.fail(
        `${file} (${sheet}) ${WORKSHEET_PART} must inflate cleanly with nothing ` +
          `following its DEFLATE stream; zlib reported ${cause.code}`
      );
    }
    assert.equal(
      inflated.length,
      central.uncompressedSize,
      `${file} (${sheet}) ${WORKSHEET_PART} declares ${central.uncompressedSize} ` +
        `uncompressed bytes and inflated to ${inflated.length}`
    );
    assert.equal(
      zlib.crc32(inflated),
      central.crc32,
      `${file} (${sheet}) ${WORKSHEET_PART} data must hash to the CRC-32 the archive ` +
        `records; stored 0x${central.crc32.toString(16)}, computed ` +
        `0x${zlib.crc32(inflated).toString(16)}`
    );
  }

  const walk = findTmpArtifacts(REPO_ROOT);

  // Completeness is asserted first: "found no artifact" only means anything
  // once every directory that could hold one has actually been read, so a
  // directory the walk could not list fails here rather than passing as clean.
  assert.deepEqual(
    walk.unverified,
    [],
    `every directory under ${REPO_ROOT} except ` +
      `${[...SKIPPED_DIRECTORIES].join(' and ')} must be readable for the ` +
      `${TMP_ARTIFACT_NAME} check to mean anything; could not inspect ` +
      `${walk.unverified.join(', ')}`
  );
  assert.deepEqual(
    walk.artifacts,
    [],
    `no ${TMP_ARTIFACT_NAME} may remain under ${REPO_ROOT}; found ${walk.artifacts.join(', ')}`
  );

  // The entries are matched on TEMP_NAMESPACE, which carries this checkout's
  // own token, so temp directories belonging to other checkouts cannot fail
  // this - and then classified by the owner pid each name declares, which is
  // what makes the assertion independent of how the runner schedules the files.
  // Under the serialized runner `verify-tests.js` uses, `test/activities.test.js`
  // has exited by the time this file runs, so its pid is dead and any directory
  // its `after` hook failed to remove is still caught; under a concurrent
  // runner that process is alive and its working directories are excluded,
  // because a directory in active use is not a failed cleanup. The invariant no
  // longer depends on the order of TEST_FILES, only on the convention the two
  // files share.
  //
  // The residual hazard, stated plainly: a dead owner's pid number can in
  // principle be reused by an unrelated process, and a leftover would then be
  // excluded here. Nothing in a test run can rely on that not happening, which
  // is why this is the backstop and not the primary alarm - that remains
  // `test/activities.test.js`'s own `after` hook, whose `fs.rmSync` throws
  // after its retries and fails that file rather than this one.
  const tempRoot = os.tmpdir();
  const { leftovers, liveSiblings } = classifyTempEntries(fs.readdirSync(tempRoot));
  assert.deepEqual(
    leftovers,
    [],
    `no ${TEMP_NAMESPACE}* entry whose owning process has exited may remain in ` +
      `${tempRoot}; found ${leftovers.join(', ')} (${liveSiblings.length} entr` +
      `${liveSiblings.length === 1 ? 'y' : 'ies'} excluded as a live sibling's ` +
      `working directory${liveSiblings.length === 0 ? '' : `: ${liveSiblings.join(', ')}`})`
  );
});
